### ISSUE TITLE
Files are not written in order they are added to the zip file

### ISSUE THREAD

**Issue by Chris7** [arjan-s/python-zipstream#3]
Because pop() is used here: https://github.com/arjan-s/python-zipstream/blob/8dca8a2a2373a2e0f131f07e7278edd4277ba529/zipstream/__init__.py#L194, streams are not consumed in the order they are added to the zipfile. This breaks for me because I have an iterable that creates an index to the asset it is generating, which is written on the subsequent `write`.

**Comment by arjan-s** [comment]
Fixed in 1.1.7
